# Generated by Django 4.0.3 on 2023-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_remove_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
