# Generated by Django 4.0.3 on 2023-05-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_referralcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='is_verified',
        ),
    ]
