# Generated by Django 4.0.3 on 2022-05-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='80ee377cf32941258a9cb9bd42fa7b34', editable=False, primary_key=True, serialize=False),
        ),
    ]
