# Generated by Django 4.0.3 on 2022-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='252a47458e35427f96aaf66701e908f2', editable=False, primary_key=True, serialize=False),
        ),
    ]
