# Generated by Django 4.0.3 on 2022-07-15 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_alter_transactionhistory_success_alter_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='d6347c9cc2d0441faf74df86bc3f8cb0', editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PendingWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
