# Generated by Django 4.0.3 on 2022-05-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transactionhistory_details_alter_wallet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='d2dd433052a54f09a7a5ba592e85f2d9', editable=False, primary_key=True, serialize=False),
        ),
    ]
