# Generated by Django 4.0.3 on 2022-07-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_number_pendingwithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='05a44225c9524b2595aac982d7a4c7dc', editable=False, primary_key=True, serialize=False),
        ),
    ]
