# Generated by Django 4.0.3 on 2022-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='51cbcd60962c4cc397bd80d3c571f418', editable=False, primary_key=True, serialize=False),
        ),
    ]
