# Generated by Django 4.0.3 on 2023-03-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='c1d540b3b0434f1e95ec2762acd4f7f3', editable=False, primary_key=True, serialize=False),
        ),
    ]
