# Generated by Django 4.0.3 on 2023-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.UUIDField(default='3e225297b75a49f59d5fb0ff00898f64', editable=False, primary_key=True, serialize=False),
        ),
    ]
