# Generated by Django 4.0.3 on 2023-05-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_wallet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingwithdrawal',
            name='status',
            field=models.CharField(default='PENDING', max_length=16),
        ),
    ]
