# Generated by Django 4.0.3 on 2022-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='f7657a3e4d2843468151cab62364ea2c', editable=False, primary_key=True, serialize=False),
        ),
    ]
