# Generated by Django 4.0.3 on 2023-03-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
    ]
